"""updated lots of fields to work with invoices

Revision ID: 78c240e9f451
Revises: 42b5b03d2cd3
Create Date: 2023-08-05 13:51:31.688053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78c240e9f451"
down_revision = "42b5b03d2cd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "date_created",
                sa.DateTime(),
                server_default=sa.text("NOW()"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("billing_address", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("billing_secondary_address", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("billing_city", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("billing_state", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("billing_zip", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("billing_country", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("billing_phone", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("billing_email", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("destination_email", sa.String(), nullable=True))

    with op.batch_alter_table("shared_with", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payrate", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("upper_limit", sa.Float(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("first_name", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(sa.Column("last_name", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("access_level", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("email", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("email")
        batch_op.drop_column("access_level")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    with op.batch_alter_table("shared_with", schema=None) as batch_op:
        batch_op.drop_column("upper_limit")
        batch_op.drop_column("payrate")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("destination_email")
        batch_op.drop_column("billing_email")
        batch_op.drop_column("billing_phone")
        batch_op.drop_column("billing_country")
        batch_op.drop_column("billing_zip")
        batch_op.drop_column("billing_state")
        batch_op.drop_column("billing_city")
        batch_op.drop_column("billing_secondary_address")
        batch_op.drop_column("billing_address")
        batch_op.drop_column("date_created")
        batch_op.drop_column("description")

    # ### end Alembic commands ###
