"""use bigint and tisd instead of int

Revision ID: f733fd42e16e
Revises: 
Create Date: 2023-07-05 14:35:48.899073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f733fd42e16e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("auth_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=32), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=32), nullable=False
        )
        batch_op.alter_column("auth_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
